name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
        shell: bash

      - name: Create SSH directory and known_hosts file
        run: |
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts

      - name: Проверка доступности сервера
        run: |
          ping -c 4 ${{ secrets.SERVER_IP }} || { echo "Сервер недоступен"; exit 1; }

      - name: Add server key to known_hosts
        run: |
          ssh-keyscan -H -t ed25519 ${{ secrets.SERVER_IP }} >> /home/runner/.ssh/known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Check Server Availability
        run: |
          ping -c 4 ${{ secrets.SERVER_IP }}

      - name: Connect to Server
        run: |
          set -e
          sshpass -p ${{ secrets.SERVER_PASS }} ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "cd front-dotg.tech/ && git pull"
        env:
          SSHPASS: ${{ secrets.SERVER_PASS }}

      - name: Restart Docker Compose
        run: |
          set -e
          sshpass -p ${{ secrets.SERVER_PASS }} ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "cd front-dotg.tech/ && docker compose build && docker compose up -d build && docker system prune -f"
